INSERT INTO TB_PESSOA (NM_PESSOA, EMAIL, DT_NASCIMENTO, CPF,TELEFONE) VALUES ('Matheus', 'matheus@gmail.com', TO_DATE('2005-04-05', 'YYYY-MM-DD'), '12345678910',1);
INSERT INTO TB_PESSOA (NM_PESSOA, EMAIL, DT_NASCIMENTO, CPF,TELEFONE) VALUES ('Ana', 'ana@gmail.com', TO_DATE('2004-04-05', 'YYYY-MM-DD'), '12345678911',2);
INSERT INTO TB_PESSOA (NM_PESSOA, EMAIL, DT_NASCIMENTO, CPF,TELEFONE) VALUES ('Mirelly', 'mirelly@gmail.com', TO_DATE('2006-04-05', 'YYYY-MM-DD'), '12345678912',3);
INSERT INTO TB_PESSOA (NM_PESSOA, EMAIL, DT_NASCIMENTO, CPF,TELEFONE) VALUES ('Beatriz', 'beatriz@gmail.com', TO_DATE('2007-04-05', 'YYYY-MM-DD'), '12345678913',4);

INSERT INTO TB_USUARIO (USERNAME, SENHA, PESSOA) VALUES ('Matheus', '$2a$12$RFh.2.xyOrxXzdVBv1p9GepT6xhY0b3pg5ue/KsELW5DpCT6MDmMy', (SELECT ID_PESSOA FROM TB_PESSOA WHERE NM_PESSOA = 'Matheus'));
INSERT INTO TB_USUARIO (USERNAME, SENHA, PESSOA) VALUES ('Ana', '$2a$12$RFh.2.xyOrxXzdVBv1p9GepT6xhY0b3pg5ue/KsELW5DpCT6MDmMy', (SELECT ID_PESSOA FROM TB_PESSOA WHERE NM_PESSOA = 'Ana'));
INSERT INTO TB_USUARIO (USERNAME, SENHA, PESSOA) VALUES ('Mirelly', '$2a$12$RFh.2.xyOrxXzdVBv1p9GepT6xhY0b3pg5ue/KsELW5DpCT6MDmMy', (SELECT ID_PESSOA FROM TB_PESSOA WHERE NM_PESSOA = 'Mirelly'));
INSERT INTO TB_USUARIO (USERNAME, SENHA, PESSOA) VALUES ('Beatriz', '$2a$12$RFh.2.xyOrxXzdVBv1p9GepT6xhY0b3pg5ue/KsELW5DpCT6MDmMy', (SELECT ID_PESSOA FROM TB_PESSOA WHERE NM_PESSOA = 'Beatriz'));
-- senha Admin
insert into role(nome) values('ROLE_ADMIN');
insert into role(nome) values('ROLE_PACIENTE');

insert into usuario_roles_associacao(id_role,id_usuario) values(1,1);
insert into usuario_roles_associacao(id_role,id_usuario) values(2,2);
insert into usuario_roles_associacao(id_role,id_usuario) values(2,3);
insert into usuario_roles_associacao(id_role,id_usuario) values(2,4);




INSERT INTO TB_EXAME (sexo,DATA, HIST_DIABETES, HIST_DOENC_CORONARIA, HIST_DOENC_VASCULAR, HIST_FUMO, HIST_HIPERTENSAO, HIST_DISLIPIDEMIA, HIST_OBESIDADE, REMED_DISLIPIDEMIA, REMED_DIABETES, REMED_HIPERTENSAO, REMED_ACEI_ARB, NVL_COLESTEROL, NVL_CREATINA, EXAM_EGFRB, PRES_SISTOLICA, PRES_DIASTOLICA, INDC_MASSA_CORP, MESES_ATE_CRISE, ANOS_ATE_CRISE, PESSOA) VALUES ('M',TO_DATE('2024-01-26', 'YYYY-MM-DD'), 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 180, 1, 85, 120, 80, 25, 0, 0, 1);
INSERT INTO TB_EXAME (sexo,DATA, HIST_DIABETES, HIST_DOENC_CORONARIA, HIST_DOENC_VASCULAR, HIST_FUMO, HIST_HIPERTENSAO, HIST_DISLIPIDEMIA, HIST_OBESIDADE, REMED_DISLIPIDEMIA, REMED_DIABETES, REMED_HIPERTENSAO, REMED_ACEI_ARB, NVL_COLESTEROL, NVL_CREATINA, EXAM_EGFRB, PRES_SISTOLICA, PRES_DIASTOLICA, INDC_MASSA_CORP, MESES_ATE_CRISE, ANOS_ATE_CRISE, PESSOA) VALUES ('F',TO_DATE('2024-02-27', 'YYYY-MM-DD'), 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 220, 1, 60, 140, 90, 23, 0, 0, 2);
INSERT INTO TB_EXAME (sexo,DATA, HIST_DIABETES, HIST_DOENC_CORONARIA, HIST_DOENC_VASCULAR, HIST_FUMO, HIST_HIPERTENSAO, HIST_DISLIPIDEMIA, HIST_OBESIDADE, REMED_DISLIPIDEMIA, REMED_DIABETES, REMED_HIPERTENSAO, REMED_ACEI_ARB, NVL_COLESTEROL, NVL_CREATINA, EXAM_EGFRB, PRES_SISTOLICA, PRES_DIASTOLICA, INDC_MASSA_CORP, MESES_ATE_CRISE, ANOS_ATE_CRISE, PESSOA) VALUES ('F',TO_DATE('2024-07-13', 'YYYY-MM-DD'), 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 240, 1, 65, 150, 95, 28, 0, 0, 4);



